kind: ServiceAccount
apiVersion: v1
metadata:
  name: lightspeed-auth
  namespace: openshift-gitops
---
apiVersion: v1
kind: Secret
metadata:
  name: lightspeed-auth-secret
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: argocd
  annotations:
    kubernetes.io/service-account.name: lightspeed-auth
type: kubernetes.io/service-account-token
