apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: openshift-gitops
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: OIDC_ARGOCD
    secretKey: oidc.keycloak.clientSecret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    creationPolicy: Merge
    deletionPolicy: Retain
    name: argocd-secret