apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: openshift-gitops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: argocd-notifications-secret
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: slack-token
      remoteRef:
        key: GITOPS_SLACK_TOKEN